name: build

on: [push, pull_request, workflow_dispatch]

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  build:
    name: "Build Cursors Themes (Arch)"
    runs-on: ubuntu-latest
    container:
      image: archlinux

    steps:
      - name: Checkout repository actions
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github/actions

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependences
        run: |
          pacman --noconfirm --noprogressbar -Syyu
          pacman --noconfirm --noprogressbar -Sy \
            xorg-xcursorgen librsvg \
            ruff python-pipx

          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Python dependences
        run: |
          pipx install uv pytest
          uv sync

      - name: Check with linter and formatter
        run: |
          ruff check
          ruff format --check

      - name: Build hyprcursor
        run: |
          uv run ./src/cursor_utils.py --hypr --log-level debug --out-dir out.hypr
          cd out.hypr && for x in Bibata-*; do \
              tar -acf ../"${x}.hypr.tar.zst" "$x"; \
          done

      - name: Build Xcursor
        run: |
          uv run ./src/cursor_utils.py --x11 --log-level debug --out-dir out.x11
          cd out.x11 && for x in Bibata-*; do \
              tar -acf ../"${x}.x11.tar.zst" "$x"; \
          done

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *.hypr.tar.zst
            *.x11.tar.zst
